spring:
  application:
    name: blog-api
  datasource:
    url: jdbc:mysql://localhost:3306/multi_module
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: "http://localhost:9081/auth/kakao/callback"
    client_secret: ${KAKAO_CLIENT_SECRET}
  naver:
    client_id: ${NAVER_CLIENT_ID}
    redirect_uri: "http://localhost:9081/auth/naver/callback"
    client_secret: ${NAVER_CLIENT_SECRET}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    redirect_uri: "http://localhost:9081/auth/google/callback"
    client_secret: ${GOOGLE_CLIENT_SECRET}

server:
  port: 9081

jwt:
  secret: ${JWT_SECRET}
