spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multi_module
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
server:
  port: 9082

